import CryptoKit
import Foundation
import GRDB
import MacClippyCore
import XCTest

extension MacClippyCoreTests {
    func testRegexAndCaptureExclusionRules() throws {
        let blocklist = try RegexBlocklist(patterns: ["password\\s*="])
        XCTAssertTrue(blocklist.matches("password = secret"))
        XCTAssertFalse(blocklist.matches("username = user"))
        XCTAssertThrowsError(try RegexBlocklist(patterns: ["["]))

        // Production default: sensitive pasteboard markers and common
        // password-manager apps are excluded. Capture All is explicit and
        // does not bypass an app exclusion.
        let safeRules = CaptureExclusionRules(excludedAppBundleIDs: ["com.Example.Passwords"])
        XCTAssertTrue(safeRules.shouldExclude(appBundleID: "com.example.passwords", pasteboardTypes: []))
        XCTAssertTrue(safeRules.shouldExclude(appBundleID: nil, pasteboardTypes: ["org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(safeRules.shouldExclude(appBundleID: nil, pasteboardTypes: ["org.nspasteboard.TransientType"]))
        XCTAssertTrue(
            safeRules.shouldExclude(appBundleID: nil, pasteboardTypes: ["org.nspasteboard.AutoGeneratedType"])
        )
        XCTAssertFalse(
            safeRules.shouldExclude(appBundleID: "com.example.editor", pasteboardTypes: ["public.utf8-plain-text"])
        )
        let privacyRules = CaptureExclusionRules(excludedTextPatterns: ["token\\s*="])
        XCTAssertTrue(privacyRules.shouldExcludeText("token = secret"))
        XCTAssertFalse(privacyRules.shouldExcludeText("username = user"))
        let malformedPrivacyRules = CaptureExclusionRules(excludedTextPatterns: ["["])
        XCTAssertTrue(malformedPrivacyRules.shouldExcludeText("ordinary text"))
        let legacyRules = CaptureExclusionRules.legacyDefault()
        XCTAssertTrue(
            legacyRules.shouldExclude(appBundleID: nil, pasteboardTypes: ["org.nspasteboard.ConcealedType"])
        )
        XCTAssertTrue(
            legacyRules.shouldExclude(appBundleID: nil, pasteboardTypes: ["org.nspasteboard.TransientType"])
        )
        XCTAssertFalse(
            legacyRules.shouldExclude(appBundleID: "com.example.editor", pasteboardTypes: ["public.utf8-plain-text"])
        )

        let captureAllRules = CaptureExclusionRules(captureAll: true)
        XCTAssertFalse(
            captureAllRules.shouldExclude(
                appBundleID: nil,
                pasteboardTypes: ["com.unknown.custom", "org.nspasteboard.ConcealedType"]
            )
        )
        XCTAssertTrue(captureAllRules.shouldExclude(appBundleID: "com.agilebits.onepassword7", pasteboardTypes: []))
    }

    func testUniversalClipboardMarkerIsNotAnExclusionType() {
        let remote = CaptureExclusionRules.remoteClipboardPasteboardType
        XCTAssertEqual(remote, "com.apple.is-remote-clipboard")
        XCTAssertFalse(CaptureExclusionRules.defaultConcealedPasteboardTypes.contains(remote))
        XCTAssertFalse(CaptureExclusionRules.defaultTransientPasteboardTypes.contains(remote))
        XCTAssertFalse(CaptureExclusionRules.defaultAutoGeneratedPasteboardTypes.contains(remote))

        let rules = CaptureExclusionRules()
        XCTAssertFalse(
            rules.shouldExclude(
                appBundleID: "com.example.editor",
                pasteboardTypes: [remote, "public.utf8-plain-text"]
            )
        )
        // Continuity items that also carry TransientType still follow the
        // default transient exclusion. Device-test that path before changing it.
        XCTAssertTrue(
            rules.shouldExclude(
                appBundleID: nil,
                pasteboardTypes: [remote, "org.nspasteboard.TransientType"]
            )
        )
        XCTAssertTrue(CaptureExclusionRules.containsRemoteClipboardMarker([remote, "public.utf8-plain-text"]))
        XCTAssertFalse(CaptureExclusionRules.containsRemoteClipboardMarker(["public.utf8-plain-text"]))
    }

    func testOCRTextIsBoundedAtStorageBoundary() throws {
        let store = try clipboardStore()
        let meta = try store.append(.image(blobID: "unused", width: 1, height: 1))
        let oversized = String(
            repeating: "ocr ",
            count: MacClippyCollectionLimits.maxOCRTextUTF8Bytes / 4 + 1
        )

        try store.setOCRText(id: meta.id, text: oversized)

        let stored = try XCTUnwrap(try store.metas(for: [meta.id]).first?.ocrText)
        XCTAssertLessThanOrEqual(stored.utf8.count, MacClippyCollectionLimits.maxOCRTextUTF8Bytes)
    }

    func testSmartTextDetectionAndTransforms() throws {
        XCTAssertEqual(SmartTextService.detect("https://example.com/a"), .url)
        XCTAssertEqual(SmartTextService.detect("person@example.com"), .email)
        XCTAssertEqual(SmartTextService.detect("#ff00aa"), .color)
        XCTAssertEqual(SmartTextService.detect("SELECT * FROM users"), .code(language: .sql))

        let cleaned = try XCTUnwrap(
            SmartTextService.cleanTrackingParameters("https://example.com?a=1&utm_source=test&gclid=x")
        )
        XCTAssertEqual(cleaned.cleaned, "https://example.com?a=1")
        XCTAssertEqual(cleaned.removedCount, 2)
        XCTAssertEqual(TextTransform.uppercase.apply(to: "hello"), "HELLO")
        XCTAssertEqual(TextTransform.trim.apply(to: "  hello \n"), "hello")
        XCTAssertEqual(TextTransform.prettyJSON.apply(to: "{\"b\":2,\"a\":1}"), "{\n  \"a\" : 1,\n  \"b\" : 2\n}")
        XCTAssertEqual(
            TextTransform.cleanTrackingURL.apply(to: "https://example.com?utm_medium=x"),
            "https://example.com"
        )
    }

    func testTextTransformDisplayNameIsNonEmptyAndStable() {
        // Every transform case must map to a non-empty human-readable label
        // so the dock Transform submenu never shows a blank item, and the
        // labels must match the user-facing names chosen for the feature.
        let expected: [TextTransform: String] = [
            .uppercase: "Uppercase",
            .lowercase: "Lowercase",
            .trim: "Trim whitespace",
            .prettyJSON: "Pretty JSON",
            .cleanTrackingURL: "Clean tracking URL"
        ]
        for transform in TextTransform.allCases {
            let name = transform.displayName
            XCTAssertFalse(name.isEmpty, "\(transform.rawValue) must have a non-empty displayName")
            XCTAssertEqual(name, expected[transform], "\(transform.rawValue) displayName changed")
        }
        // The label set must stay in sync with CaseIterable so a future case
        // is not silently missing a label.
        XCTAssertEqual(TextTransform.allCases.count, expected.count)
    }

    func testCategoryColorUsesExplicitColorOrDeterministicFallback() throws {
        let id = try XCTUnwrap(RecordID(rawValue: "0123456789ABCDEFGHJKMNPQRS"))
        let board = Pinboard(id: id, name: "Work")

        XCTAssertEqual(MacClippyCategoryColorPolicy.color(for: board), MacClippyCategoryColorPolicy.color(for: board))
        XCTAssertEqual(
            MacClippyCategoryColorPolicy.color(for: Pinboard(id: id, name: "Work", color: "#123456")),
            "#123456"
        )
        XCTAssertEqual(
            MacClippyCategoryColorPolicy.color(for: Pinboard(id: id, name: "Work", color: "  ")),
            MacClippyCategoryColorPolicy.color(for: board)
        )
    }

    func testCategoryPaletteUsesAppleInspiredSemanticNames() {
        XCTAssertEqual(
            MacClippyCategoryColorPolicy.palette,
            ["#0A84FF", "#BF5AF2", "#FF375F", "#FF453A", "#FF9F0A", "#FFD60A", "#30D158", "#8E8E93"]
        )
        XCTAssertEqual(
            MacClippyCategoryColorPolicy.palette.map(MacClippyCategoryColorPolicy.name),
            ["blue", "purple", "pink", "red", "orange", "yellow", "green", "graphite"]
        )
        XCTAssertEqual(
            MacClippyCategoryColorPolicy.palette.map(MacClippyCategoryColorPolicy.displayName),
            ["Blue", "Purple", "Pink", "Red", "Orange", "Yellow", "Green", "Graphite"]
        )
        XCTAssertEqual(MacClippyCategoryColorPolicy.name(for: "#FFFFFF"), "custom color")
        XCTAssertEqual(MacClippyCategoryColorPolicy.displayName(for: "#FFFFFF"), "Custom")
    }

    func testCollectionListDoesNotTreatWrongKeyAsEmptyData() throws {
        let key = testKey()
        let wrongKey = SymmetricKey(data: Data(repeating: 7, count: 32))

        let pinboardDatabase = try MacClippyDatabase(inMemory: true)
        let pinboards = try PinboardStore(database: pinboardDatabase, deviceKey: key)
        _ = try pinboards.create(name: "Protected")
        let wrongPinboards = try PinboardStore(database: pinboardDatabase, deviceKey: wrongKey)
        XCTAssertThrowsError(try wrongPinboards.list()) { error in
            XCTAssertEqual(error as? MacClippyCipherError, .openFailed)
        }

        let snippetDatabase = try MacClippyDatabase(inMemory: true)
        let snippets = try SnippetStore(database: snippetDatabase, deviceKey: key)
        _ = try snippets.create(name: "Protected", body: "secret")
        let wrongSnippets = try SnippetStore(database: snippetDatabase, deviceKey: wrongKey)
        XCTAssertThrowsError(try wrongSnippets.list()) { error in
            XCTAssertEqual(error as? MacClippyCipherError, .openFailed)
        }
    }

    func testClipboardDropPolicyParsesIDsAndTreatsDuplicatesAsSafeNoOp() throws {
        let id = try XCTUnwrap(RecordID(rawValue: "0123456789ABCDEFGHJKMNPQRS"))

        XCTAssertEqual(MacClippyClipboardDropPolicy.recordID(from: "  \(id.rawValue)\n"), id)
        XCTAssertEqual(MacClippyClipboardDropPolicy.decision(for: id.rawValue, existingIDs: []), .accept)
        XCTAssertEqual(MacClippyClipboardDropPolicy.decision(for: id.rawValue, existingIDs: [id]), .duplicate)
        XCTAssertEqual(MacClippyClipboardDropPolicy.decision(for: "invalid", existingIDs: []), .invalid)
    }

    func testDeviceKeyUsesInjectedKeychain() throws {
        let keychain = InMemoryKeychain()
        let first = try MacClippyDeviceKey(keychain: keychain).deviceKey()
        let second = try MacClippyDeviceKey(keychain: keychain).deviceKey()
        XCTAssertEqual(first.withUnsafeBytes { Data($0) }, second.withUnsafeBytes { Data($0) })
        XCTAssertEqual(MacClippySystemKeychain.service, "com.macallyouneed.macclippy.device-key")
    }

    func testDeviceKeyDoesNotRegenerateWhenExistingStorageHasNoKey() throws {
        let keychain = InMemoryKeychain()

        XCTAssertThrowsError(
            try MacClippyDeviceKey(keychain: keychain).deviceKey(requireExistingStorage: true)
        ) { error in
            guard case MacClippyKeychainError.missingKey = error else {
                return XCTFail("expected missingKey, got \(error)")
            }
        }
        XCTAssertNil(try keychain.get(MacClippyDeviceKey.account))
    }

    func testBatchBodyReadReportsMalformedRowsAsCorruption() throws {
        let database = try MacClippyDatabase(inMemory: true)
        let store = try ClipboardStore(database: database, deviceKey: testKey())
        let id = RecordID.generate()

        try database.queue.write { connection in
            try connection.execute(
                sql: "INSERT INTO clipboard_records (id, created, modified, device_id, lamport, kind, content_kind, "
                    + "preview, envelope) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                arguments: [
                    id.rawValue,
                    1,
                    1,
                    "device",
                    1,
                    "clipboard",
                    MacClippyContentKind.text.rawValue,
                    "malformed",
                    Data()
                ]
            )
        }

        XCTAssertThrowsError(try store.bodies(for: [id])) { error in
            guard case MacClippyCipherError.invalidEnvelope = error else {
                return XCTFail("expected invalidEnvelope, got \(error)")
            }
        }
    }
}
